#
#

NOM=libmlx.a
SRC= mlx_shaders.c mlx_new_window.m mlx_init_loop.m mlx_new_image.m mlx_xpm.c mlx_int_str_to_wordtab.c
SRC+= mlx_png.c mlx_mouse.m
OBJ1=$(SRC:.c=.o)
OBJ=$(OBJ1:.m=.o)
CFLAGS+=-O2

# Colors
GR	= \033[32;1m
RE	= \033[31;1m
YE	= \033[33;1m
CY	= \033[36;1m
RC	= \033[0m

# add to match string put with X11 in size and position
CFLAGS+= -DSTRINGPUTX11

all: $(NOM)

$(NOM):	$(OBJ)
	@printf "$(GR)=== Archiving $(NOM) ===$(RC)\n"
	@ar -r $(NOM) $(OBJ)
	@ranlib $(NOM)
	@printf "$(YE)=== $(NOM) created ===$(RC)\n"

clean:
	rm -f $(NOM) $(OBJ) *~
	rm -f mlx_app

re: clean all
